apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wordpress.fullname" . }}-mariadb
  labels:
    app: {{ include "wordpress.name" . }}
    chart: {{ include "wordpress.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - {{ .Values.mariadb.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.mariadb.persistence.size }}
  storageClassName: {{ .Values.mariadb.persistence.storageClass }}
