apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress.fullname" . }}-mariadb
  labels:
    app: {{ include "wordpress.name" . }}
    chart: {{ include "wordpress.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  mariadb-root-password: {{ .Values.mariadb.db.rootPassword | b64enc | quote }}
  mariadb-password: {{ .Values.mariadb.db.password | b64enc | quote }}
